language: "perl"
perl:
  - "5.22"
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
before_install:
  - git clone https://github.com/frankiejol/Test-SQL-Data.git ~/Test-SQL-Data
  - cd ~/Test-SQL-Data
  - perl Makefile.PL
  - make install
install:
  - cpan-install YAML
script: "perl Makefile.PL && make test"
# branches:
#   only:
#     - master
#env:
#group: "stable"
group: "edge"
#dist: "zesty"
#dist: "yakkety"
dist: "trusty"
